<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Defines constants so they can be accessed both from lib.php and testing code
 *
 * @package mod_openstudio
 * @copyright The Open University
 * @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

define('OPENSTUDIO_DEFAULT_MAXBYTES', 10485760); // Default to 10MB.
define('OPENSTUDIO_DEFAULT_SITENAME_LENGTH', 64);
define('OPENSTUDIO_DEFAULT_NAVITEM_LENGTH', 15);
define('OPENSTUDIO_DEFAULT_BLOCKNAME', 'block');
define('OPENSTUDIO_DEFAULT_BLOCKSNAME', 'blocks');
define('OPENSTUDIO_DEFAULT_ACTIVITYNAME', 'activity');
define('OPENSTUDIO_DEFAULT_ACTIVITIESNAME', 'activities');
define('OPENSTUDIO_DEFAULT_CONTENTNAME', 'content');
define('OPENSTUDIO_DEFAULT_CONTENTSNAME', 'contents');
define('OPENSTUDIO_DEFAULT_BLOCKLEVELCONTAINER', 1);
define('OPENSTUDIO_DEFAULT_ACTIVITYLEVELCONTAINER', 2);
define('OPENSTUDIO_DEFAULT_CONTENTLEVELCONTAINER', 3);
define('OPENSTUDIO_DEFAULT_CONTENTTHUMBNAIL_WIDTH', 542);
define('OPENSTUDIO_DEFAULT_STREAMPAGESIZE', 12);
define('OPENSTUDIO_DEFAULT_ACIVITYPAGESIZE', 20);
define('OPENSTUDIO_DEFAULT_PEOPLEPAGESIZE', 10);
define('OPENSTUDIO_DEFAULT_CONTENTVERSIONSTOSHOW', 4);
define('OPENSTUDIO_DEFAULT_EXPORTPAGESIZE', 10);
define('OPENSTUDIO_DEFAULT_MAXPINBOARDCONTENTS', 10);
define('OPENSTUDIO_DEFAULT_MAXCONTENTVERSIONS', 5);
define('OPENSTUDIO_DEFAULT_MAXPINBOARDCONTENTSLLENGTH', 3); // 3 = 999 maximum.
define('OPENSTUDIO_DEFAULT_MAXCONTENTVERSIONSLENGTH', 2); // 2 = 99 maximum.
define('OPENSTUDIO_DEFAULT_CONTENTCOMMENTLENGTH', 5000);
define('OPENSTUDIO_DEFAULT_CONTENTVIEWIMAGESIZELIMIT', 524288); // Maximum size image: 524288b or 1048576b.
define('OPENSTUDIO_DEFAULT_SUBSCRIPTIONEMAILTOSENDPERSTUDIOPERCRONRUN', 100);
define('OPENSTUDIO_DEFAULT_SUBSCRIPTIONTOPROCESSPERCRONRUN', 1000);
define('OPENSTUDIO_DEFAULT_MAXPINBOARDFOLDERSCONTENTS', 10);
define('OPENSTUDIO_DEFAULT_MAXPINBOARDFOLDERSCONTENTSLENGTH', 3); // 3 = 999 maximum.
define('OPENSTUDIO_DEFAULT_FOLDERTEMPLATEADDITIONALCONTENTS', 10);

define('OPENSTUDIO_FEATURE_MODULE', 1);
define('OPENSTUDIO_FEATURE_GROUP', 2);
define('OPENSTUDIO_FEATURE_STUDIO', 4);
define('OPENSTUDIO_FEATURE_PINBOARD', 8);
define('OPENSTUDIO_FEATURE_CONTENTTEXTUSESHTML', 16);
define('OPENSTUDIO_FEATURE_CONTENTCOMMENTUSESHTML', 32);
define('OPENSTUDIO_FEATURE_CONTENTCOMMENTUSESAUDIO', 64);
define('OPENSTUDIO_FEATURE_CONTENTUSESFILEUPLOAD', 128);
define('OPENSTUDIO_FEATURE_ENABLECOLLECTIONS', 256);
define('OPENSTUDIO_FEATURE_ENABLERSS', 512);
define('OPENSTUDIO_FEATURE_ENABLESUBSCRIPTION', 1024);
define('OPENSTUDIO_FEATURE_ENABLEEXPORTIMPORT', 2048);
define('OPENSTUDIO_FEATURE_CONTENTUSESWEBLINK', 4096);
define('OPENSTUDIO_FEATURE_CONTENTUSESEMBEDCODE', 8192);
define('OPENSTUDIO_FEATURE_CONTENTRECIPROCALACCESS', 16384);
define('OPENSTUDIO_FEATURE_ENABLELOCK', 32768);
define('OPENSTUDIO_FEATURE_ENABLEFOLDERS', 65536);
define('OPENSTUDIO_FEATURE_CONTENTALLOWNOTEBOOKS', 131072);
define('OPENSTUDIO_FEATURE_ENABLEFOLDERSANYCONTENT', 262144);
define('OPENSTUDIO_FEATURE_PARTICIPATIONSMILEY', 524288);

define('OPENSTUDIO_PARTICPATION_FLAG_ALERT', 1);
define('OPENSTUDIO_PARTICPATION_FLAG_FAVOURITE', 2);
define('OPENSTUDIO_PARTICPATION_FLAG_NEEDHELP', 3);
define('OPENSTUDIO_PARTICPATION_FLAG_MADEMELAUGH', 4);
define('OPENSTUDIO_PARTICPATION_FLAG_INSPIREDME', 5);
define('OPENSTUDIO_PARTICPATION_FLAG_READ_CONTENT', 6);
define('OPENSTUDIO_PARTICPATION_FLAG_FOLLOW_CONTENT', 7);
define('OPENSTUDIO_PARTICPATION_FLAG_FOLLOW_USER', 8);
define('OPENSTUDIO_PARTICPATION_FLAG_COMMENT', 9);
define('OPENSTUDIO_PARTICPATION_FLAG_COMMENT_LIKE', 10);

define('OPENSTUDIO_TRACKING_CREATE_CONTENT', 1);
define('OPENSTUDIO_TRACKING_READ_CONTENT', 2);
define('OPENSTUDIO_TRACKING_READ_CONTENT_VERSION', 3);
define('OPENSTUDIO_TRACKING_DELETE_CONTENT', 4);
define('OPENSTUDIO_TRACKING_DELETE_CONTENT_VERSION', 5);
define('OPENSTUDIO_TRACKING_UPDATE_CONTENT', 6);
define('OPENSTUDIO_TRACKING_UPDATE_CONTENT_VISIBILITY_PRIVATE', 7);
define('OPENSTUDIO_TRACKING_UPDATE_CONTENT_VISIBILITY_GROUP', 8);
define('OPENSTUDIO_TRACKING_UPDATE_CONTENT_VISIBILITY_MODULE', 9);
define('OPENSTUDIO_TRACKING_UPDATE_CONTENT_VISIBILITY_TUTOR', 16);
define('OPENSTUDIO_TRACKING_ARCHIVE_CONTENT', 10);
define('OPENSTUDIO_TRACKING_MODIFY_FOLDER', 11);
define('OPENSTUDIO_TRACKING_COPY_CONTENT', 12);
define('OPENSTUDIO_TRACKING_ADD_CONTENT_TO_FOLDER', 13);
define('OPENSTUDIO_TRACKING_LINK_CONTENT_TO_FOLDER', 14);
define('OPENSTUDIO_TRACKING_COPY_CONTENT_TO_FOLDER', 15);

define('OPENSTUDIO_FILTER_SCOPE_EVERYONE', 1);
define('OPENSTUDIO_FILTER_SCOPE_MY', 2);
define('OPENSTUDIO_FILTER_SCOPE_THEIRS', 3);

define('OPENSTUDIO_FILTER_FLAG_EMPTYCONTENT', 1);
define('OPENSTUDIO_FILTER_FLAG_NOTREAD', 2);
define('OPENSTUDIO_FILTER_FLAG_FAVOURITES', 3);
define('OPENSTUDIO_FILTER_FLAG_MOSTPOPULAR', 4);
define('OPENSTUDIO_FILTER_FLAG_HELPME', 5);
define('OPENSTUDIO_FILTER_FLAG_MOSTSMILES', 6);
define('OPENSTUDIO_FILTER_FLAG_MOSTINSPIRATION', 7);
define('OPENSTUDIO_FILTER_FLAG_COMMENTS', 8);
define('OPENSTUDIO_FILTER_FLAG_READ', 9);
define('OPENSTUDIO_FILTER_FLAG_LOCKED', 10);
define('OPENSTUDIO_FILTER_FLAG_TUTOR', 11);

define('OPENSTUDIO_VIEW_MODE_MORTAR', 1);
define('OPENSTUDIO_VIEW_MODE_GRID', 2);
define('OPENSTUDIO_VIEW_MODE_PEOPLE', 3);
define('OPENSTUDIO_VIEW_MODE_ACTIVITY', 4);

define('OPENSTUDIO_SORT_ASC', 1);
define('OPENSTUDIO_SORT_DESC', 0);

define('OPENSTUDIO_SORT_FLAG_DATE', 1);
define('OPENSTUDIO_SORT_FLAG_USERNAME', 2);
define('OPENSTUDIO_SORT_FLAG_ACTIVITYTITLE', 3);
define('OPENSTUDIO_SORT_FLAG_COMMENTNUMBRS', 4);

define('OPENSTUDIO_FILTER_PEOPLE_GROUP', 0);
define('OPENSTUDIO_FILTER_PEOPLE_MODULE', 1);

define('OPENSTUDIO_SORT_PEOPLE_NAME', 2);
define('OPENSTUDIO_SORT_PEOPLE_ACTIVTY', 1);
define('OPENSTUDIO_SORT_PEOPLE_ASKINGFORHELP', 4);

define('OPENSTUDIO_VISIBILITY_PRIVATE', 1);
define('OPENSTUDIO_VISIBILITY_GROUP', 2);
define('OPENSTUDIO_VISIBILITY_MODULE', 3);
define('OPENSTUDIO_VISIBILITY_WORKSPACE', 4);
define('OPENSTUDIO_VISIBILITY_PRIVATE_PINBOARD', 5);
define('OPENSTUDIO_VISIBILITY_INFOLDERONLY', 6);
define('OPENSTUDIO_VISIBILITY_TUTOR', 7);

define('OPENSTUDIO_CONTENT_IN_MOODLE_STORAGE', '0');

define('OPENSTUDIO_CONTENTTYPE_NONE', 0);
define('OPENSTUDIO_CONTENTTYPE_TEXT', 5);
define('OPENSTUDIO_CONTENTTYPE_IMAGE', 10);
define('OPENSTUDIO_CONTENTTYPE_IMAGE_EMBED', 11);
define('OPENSTUDIO_CONTENTTYPE_VIDEO', 20);
define('OPENSTUDIO_CONTENTTYPE_VIDEO_EMBED', 21);
define('OPENSTUDIO_CONTENTTYPE_AUDIO', 30);
define('OPENSTUDIO_CONTENTTYPE_AUDIO_EMBED', 31);
define('OPENSTUDIO_CONTENTTYPE_DOCUMENT', 40);
define('OPENSTUDIO_CONTENTTYPE_DOCUMENT_EMBED', 41);
define('OPENSTUDIO_CONTENTTYPE_PRESENTATION', 50);
define('OPENSTUDIO_CONTENTTYPE_PRESENTATION_EMBED', 51);
define('OPENSTUDIO_CONTENTTYPE_SPREADSHEET', 60);
define('OPENSTUDIO_CONTENTTYPE_SPREADSHEET_EMBED', 61);
define('OPENSTUDIO_CONTENTTYPE_URL', 70);
define('OPENSTUDIO_CONTENTTYPE_URL_IMAGE', 71);
define('OPENSTUDIO_CONTENTTYPE_URL_VIDEO', 72);
define('OPENSTUDIO_CONTENTTYPE_URL_AUDIO', 73);
define('OPENSTUDIO_CONTENTTYPE_URL_DOCUMENT', 74);
define('OPENSTUDIO_CONTENTTYPE_URL_DOCUMENT_PDF', 75);
define('OPENSTUDIO_CONTENTTYPE_URL_DOCUMENT_DOC', 76);
define('OPENSTUDIO_CONTENTTYPE_URL_PRESENTATION', 77);
define('OPENSTUDIO_CONTENTTYPE_URL_PRESENTATION_PPT', 78);
define('OPENSTUDIO_CONTENTTYPE_URL_SPREADSHEET', 79);
define('OPENSTUDIO_CONTENTTYPE_URL_SPREADSHEET_XLS', 80);
define('OPENSTUDIO_CONTENTTYPE_COLLECTION', 90);
define('OPENSTUDIO_CONTENTTYPE_FOLDER', 100);
define('OPENSTUDIO_CONTENTTYPE_FOLDER_CONTENT', 110);

define('OPENSTUDIO_OWNERSHIP_MYOWNWORK', 0);
define('OPENSTUDIO_OWNERSHIP_FOUNDONLINE', 1);
define('OPENSTUDIO_OWNERSHIP_FOUNDELSEWHERE', 2);

define('OPENSTUDIO_CONTENT_INFO_GPSDATA', 1);
define('OPENSTUDIO_CONTENT_INFO_IMAGEDATA', 2);

define('OPENSTUDIO_FEED_TYPE_PINBOARD', 0);
define('OPENSTUDIO_FEED_TYPE_ACTIVITY', 1);
define('OPENSTUDIO_FEED_TYPE_GROUP', 2);
define('OPENSTUDIO_FEED_TYPE_MODULE', 3);
define('OPENSTUDIO_FEED_TYPE_CONTENT', 4);

define('OPENSTUDIO_SUBSCRIPTION_GROUP', 1);
define('OPENSTUDIO_SUBSCRIPTION_MODULE', 2);
define('OPENSTUDIO_SUBSCRIPTION_CONTENT', 3);

define ('OPENSTUDIO_SUBSCRIPTION_FORMAT_HTML', 1);
define ('OPENSTUDIO_SUBSCRIPTION_FORMAT_PLAIN', 2);

define('OPENSTUDIO_SUBSCRIPTION_FREQUENCY_HOURLY', 1);
define('OPENSTUDIO_SUBSCRIPTION_FREQUENCY_DAILY', 2);

define('OPENSTUDIO_SESSION_CLIPBOARD', 'studioclipboard');
define('OPENSTUDIO_SESSION_COLLECTION', 'studiocollection');

define('OPENSTUDIO_LEVELS_STATUS_DEFAULT', 0);
define('OPENSTUDIO_LEVELS_STATUS_SOFT_DELETED', -1);

define('OPENSTUDIO_FOLDER_PERMISSION_REORDER', 1);

define('OPENSTUDIO_FOLDER_CONTENT_PROVENANCE_COPY', 0);
define('OPENSTUDIO_FOLDER_CONTENT_PROVENANCE_EDITED', 1);
define('OPENSTUDIO_FOLDER_CONTENT_PROVENANCE_UNLINKED', 2);

define('OPENSTUDIO_CONTENT_ITEM_CONTAINER_CONTENT', 0);
define('OPENSTUDIO_CONTENT_ITEM_CONTAINER_VERSION', 1);

// Locktype is an integer with the following values.
define('OPENSTUDIO_UNLOCK', 0);
define('OPENSTUDIO_LOCKED_ALL', 1);// Combination of 2, 4 and 8.
define('OPENSTUDIO_LOCKED_CRUD', 2);// Cannot edit/delete/archive content.
define('OPENSTUDIO_LOCKED_SOCIAL', 4);// Cannot do social flagging (favourite, inspire, etc.).
define('OPENSTUDIO_LOCKED_COMMENT', 8);// Cannot have new comments.
define('OPENSTUDIO_LOCKED_SOCIAL_CRUD', 6);// Combination of 2 and 4.
define('OPENSTUDIO_LOCKED_COMMENT_CRUD', 12);// Combination of 2 and 8.

